名称:刷课

在:
推:
分支:[主要的]
#是否开始每天8点定时刷课，若要开启请把下面两行注释去掉
#时间表：
#-cron:“0 8***”

工作:
起点:
运行:ubuntu最新# 在最新版本的 Ubuntu 操作系统环境下运行
步骤:#要执行的步骤
-名称:拷贝代码
使用:行动/签出@v3# 用于将github代码仓库的代码拷贝到工作目录中

-名称:设置python环境
使用:行动/setup-python@v2# 用于设置 Python 环境，它允许你指定要在工作环境中使用的 Python 版本
具有:
python版本:&#39;3.9&#39;# 选择要用的Python版本

-名称:安装依赖包
运行:|#安装依赖包
pip安装-r/要求.txt


-名称:运行main.py
运行:python main.py -u 18777823783 -p qwer5720 -l 249869863#课程id
